name: Deploy to GCP  
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        GCP_USER: ${{ secrets.GCP_USER }}
        GCP_HOST: ${{ secrets.GCP_HOST }}
      run: 
        echo Hello,world
        pwd

        #echo "$SECRET_KEY" > secret_key
        #chmod 600 secret_key
        #ssh -oStrictHostKeyChecking=no ${GCP_USER}@${GCP_HOST} -i secret_key "cd ~/home/takeshi/CSV && sudo git pull origin master"
